services:
  app:
    build: .
    container_name: springboot
    expose:
      - 8080
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: ""
    command: >
      /bin/sh -c "
      certbot certonly --webroot -w /var/www/certbot
      --email bobbyokolie14@gmail.com --agree-tos --no-eff-email
      --force-renewal -d neighborlyunion.com -d www.neighborlyunion.com
      && while true; do sleep 12h; certbot renew; done"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge